# XNXGAMES_Auth

# Port    
server:
  port: 9090
  
# DB
spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2://192.168.99.101:8080/keycloak
    username: sa
  jpa:
    show-sql: true
  
keycloak:  realm: XNXGAMES
  resource: xnxgames_web
  auth-server-url: http://192.168.99.101:8080/auth
  public-client: true
  ssl-required: none
  principal-attribute: preferred_username
  bearer-only: true